/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coquitastore.graficos;

import coquitastore.datos.UsuarioDAO;
import coquitastore.domain.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class AltaUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaUser
     */
    public AltaUser() {
        initComponents();
        jComboBoxTipoUsuario.addItem("ADM");
        jComboBoxTipoUsuario.addItem("VEN");
        jComboBoxTipoUsuario.addItem("REP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoUsuario = new javax.swing.JComboBox<>();
        jPasswordFieldConPassword = new javax.swing.JPasswordField();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 204));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Usuario");
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(null);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(321, 143, 168, 30);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar);
        jButtonAceptar.setBounds(310, 320, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("   Alta de Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(264, 19, 156, 22);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 150, 80, 20);

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 190, 80, 20);

        jLabel4.setText("Confirmar Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 220, 130, 30);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar);
        jButtonCerrar.setBounds(410, 320, 80, 30);

        jLabelTipoUsuario.setText("Seleccione un tipo de Usuario:");
        getContentPane().add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(140, 270, 170, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coquitastore/graficos/iconos/idk.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 10, 90, 90);

        jComboBoxTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoUsuario);
        jComboBoxTipoUsuario.setBounds(320, 260, 168, 30);

        jPasswordFieldConPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldConPassword);
        jPasswordFieldConPassword.setBounds(320, 220, 170, 30);
        getContentPane().add(jPasswordFieldContrasenia);
        jPasswordFieldContrasenia.setBounds(320, 180, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        String nombre=jTextFieldNombre.getText();
        String password=jPasswordFieldContrasenia.getText();
        String conpassword=jPasswordFieldConPassword.getText();
        String tipoUsuario=jComboBoxTipoUsuario.getSelectedItem().toString();
        
        UsuarioDAO usuarioDAO= new UsuarioDAO ();
       Usuario nuevoUsuario=new Usuario (nombre, password, tipoUsuario);
      
        
        if(password.equals(conpassword)){
            System.out.println("Las contraseñas coinciden");
            try {
                usuarioDAO.insertar(nuevoUsuario);
               
            } catch (SQLException ex) {
                Logger.getLogger(AltaUser.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Revisar el siguiente error:" + ex);
            }
        } else {
        System.out.println("Las contraseñas no coinciden");
          JOptionPane.showMessageDialog(null, "Las contraseña no coinciden");
        
              
    }//GEN-LAST:event_jButtonAceptarActionPerformed
    }
    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoUsuarioActionPerformed

    private void jPasswordFieldConPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBoxTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JPasswordField jPasswordFieldConPassword;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
